anchor_scales:
- 4
- 8
- 16
- 32
- 64
- 128
- 512
base_model: attention
cls_loss: focal
device: cuda
incomplete_iou_thresh: 0.3
incomplete_sample_ratio: 1.0
lambda_ctr: 5.0
lambda_reg: 10.0
log_file: log.txt
lr: 0.001
max_epoch: 300
model: anchor-based
model_dir: ./models/ab_basic/
neg_iou_thresh: 0.0
neg_sample_ratio: 2.0
nms_thresh: 0.5
num_feature: 1024
num_head: 8
num_hidden: 512
pos_iou_thresh: 0.6
reg_loss: soft-iou
seed: 2021
splits:
- ./splits/tvsum.yml
- ./splits/summe.yml
weight_decay: 1.0e-05
